# syntax=docker/dockerfile:1
# Copyright 2026 University of Augsburg, Chair of Mechatronics by Noah Böckmann
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG ROS_DISTRO=jazzy
FROM ros:${ROS_DISTRO}-ros-base

ENV DEBIAN_FRONTEND=noninteractive

# Install build tools
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
        git \
        python3-colcon-common-extensions \
        python3-vcstool \
        wget

WORKDIR /ros2_ws

COPY smolvla_ur10e_real.repos src/smolvla_ur10e_real.repos

# Clone external repositories
RUN vcs import src < src/smolvla_ur10e_real.repos

# Install dependencies using rosdep
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    . /opt/ros/${ROS_DISTRO}/setup.sh \
    && apt-get update \
    && rosdep update \
    && rosdep install --from-paths src --ignore-src --skip-keys robotiq_hande_description -y

# Build the workspace
RUN . /opt/ros/${ROS_DISTRO}/setup.sh \
    && colcon build \
        --symlink-install \
        --packages-skip cartesian_controller_simulation cartesian_controller_tests cartesian_compliance_controller cartesian_force_controller \
        --cmake-args -DCMAKE_BUILD_TYPE=Release

# Ensure the workspace is sourced
RUN echo "source /ros2_ws/install/setup.bash" >> /root/.bashrc

CMD ["sleep", "infinity"]